In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'C:\Users\Shivam Bobate\OneDrive\Desktop\internship project\WA_Fn-UseC_-HR-Employee-Attrition.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [4]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [5]:
df.iloc[:, 9:25].head(10)

,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating
0,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3
1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4
2,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3
3,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3
4,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3
5,8,4,Male,79,3,1,Laboratory Technician,4,Single,3068,11864,0,Y,No,13,3
6,10,3,Female,81,4,1,Laboratory Technician,1,Married,2670,9964,4,Y,Yes,20,4
7,11,4,Male,67,3,1,Laboratory Technician,3,Divorced,2693,13335,1,Y,No,22,4
8,12,4,Male,44,2,3,Manufacturing Director,3,Single,9526,8787,0,Y,No,21,4
9,13,3,Male,94,3,2,Healthcare Representative,3,Married,5237,16577,6,Y,No,13,3

In [6]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [7]:
df.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [8]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [9]:
df.iloc[:, 9:25].describe()

,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,1024.865306,2.721769,65.891156,2.729932,2.063946,2.728571,6502.931293,14313.103401,2.693197,15.209524,3.153741
std,602.024335,1.093082,20.329428,0.711561,1.106940,1.102846,4707.956783,7117.786044,2.498009,3.659938,0.360824
min,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1009.000000,2094.000000,0.000000,11.000000,3.000000
25%,491.250000,2.000000,48.000000,2.000000,1.000000,2.000000,2911.000000,8047.000000,1.000000,12.000000,3.000000
50%,1020.500000,3.000000,66.000000,3.000000,2.000000,3.000000,4919.000000,14235.500000,2.000000,14.000000,3.000000
75%,1555.750000,4.000000,83.750000,3.000000,3.000000,4.000000,8379.000000,20461.500000,4.000000,18.000000,3.000000
max,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,19999.000000,26999.000000,9.000000,25.000000,4.000000

In [10]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [11]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [12]:
# Returns True if all rows have the same value, False otherwise
is_uniform = df['Over18'].nunique() == 1
is_uniform

True

In [13]:
df.drop(columns=['EmployeeCount', 'Over18', 'StandardHours'], inplace=True)

In [14]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [15]:
#create a column age_group
labels = ['Young Adult','Adult', 'Middle-aged', 'Senior']
df['Age_group'] = pd.qcut(df['Age'], q=4, labels=labels)

In [16]:
df[['Age', 'Age_group']].head(15)

    Age    Age_group
0    41  Middle-aged
1    49       Senior
2    37  Middle-aged
3    33        Adult
4    27  Young Adult
5    32        Adult
6    59       Senior
7    30  Young Adult
8    38  Middle-aged
9    36        Adult
10   35        Adult
11   29  Young Adult
12   31        Adult
13   34        Adult
14   28  Young Adult

In [17]:
#create a new column Education_level
education_labels = {
    1: 'Below College',
    2: 'College',
    3: 'Bachelor',
    4: 'Master',
    5: 'Doctor'
}
df['Education_level'] = df['Education'].map(education_labels)

In [18]:
df[['Education', 'Education_level']].head()

   Education Education_level
0          2         College
1          1   Below College
2          2         College
3          4          Master
4          1   Below College

In [19]:
#create a new column of environmentsatisfaction_level
EnvironmentSatisfaction_labels = {1: 'Low', 2: 'Medium', 3: 'High', 4: 'Very High'}
df['EnvironmentSatisfaction_level'] = df['EnvironmentSatisfaction'].map(EnvironmentSatisfaction_labels)

In [20]:
df[['EnvironmentSatisfaction', 'EnvironmentSatisfaction_level']].head()

   EnvironmentSatisfaction EnvironmentSatisfaction_level
0                        2                        Medium
1                        3                          High
2                        4                     Very High
3                        4                     Very High
4                        1                           Low

In [21]:
#create a new column Jobinvolvement_level
JobLevel_labels = {
    1: 'Low',
    2: 'Medium',
    3: 'High',
    4: 'Very High'
}
df['JobInvolvement_level'] = df['JobInvolvement'].map(JobLevel_labels)

In [22]:
df[['JobInvolvement', 'JobInvolvement_level']].head()

   JobInvolvement JobInvolvement_level
0               3                 High
1               2               Medium
2               2               Medium
3               3                 High
4               3                 High

In [23]:
#create a new column Jobsatisfaction_level
Jobsatisfaction_labels = {
    1: 'Low',
    2: 'Medium',
    3: 'High',
    4: 'Very High'
}
df['JobSatisfaction_level'] = df['JobSatisfaction'].map(Jobsatisfaction_labels)

In [24]:
df[['JobSatisfaction', 'JobSatisfaction_level']].head()

   JobSatisfaction JobSatisfaction_level
0                4             Very High
1                2                Medium
2                3                  High
3                3                  High
4                2                Medium

In [25]:
#create a new column PerformanceRating_level
PerformanceRating_labels = {
1: 'Low',
2: 'Good',
3: 'Excellent',
4: 'Outstanding'
}
df['PerformanceRating_level'] = df['PerformanceRating'].map(PerformanceRating_labels)

In [26]:
df[['PerformanceRating', 'PerformanceRating_level']].head()

   PerformanceRating PerformanceRating_level
0                  3               Excellent
1                  4             Outstanding
2                  3               Excellent
3                  3               Excellent
4                  3               Excellent

In [27]:
#create a new column RelationshipSatisfaction_level
RelationshipSatisfaction_labels = {
1: 'Low',
2: 'Medium',
3: 'High',
4: 'Very High'
}
df['RelationshipSatisfaction_level'] = df['RelationshipSatisfaction'].map(RelationshipSatisfaction_labels)

In [28]:
df[['RelationshipSatisfaction', 'RelationshipSatisfaction_level']].head()

   RelationshipSatisfaction RelationshipSatisfaction_level
0                         1                            Low
1                         4                      Very High
2                         2                         Medium
3                         3                           High
4                         4                      Very High

In [29]:
#create a new column WorkLifeBalance_level
WorkLifeBalance_labels = {
1: 'Bad',
2: 'Good',
3: 'Better',
4: 'Best'
}
df['WorkLifeBalance_level'] = df['WorkLifeBalance'].map(WorkLifeBalance_labels)

In [30]:
df[['WorkLifeBalance', 'WorkLifeBalance_level']].head()

   WorkLifeBalance WorkLifeBalance_level
0                1                   Bad
1                3                Better
2                3                Better
3                3                Better
4                3                Better

In [31]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,YearsSinceLastPromotion,YearsWithCurrManager,Age_group,Education_level,EnvironmentSatisfaction_level,JobInvolvement_level,JobSatisfaction_level,PerformanceRating_level,RelationshipSatisfaction_level,WorkLifeBalance_level
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,0,5,Middle-aged,College,Medium,High,Very High,Excellent,Low,Bad
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,1,7,Senior,Below College,High,Medium,Medium,Outstanding,Very High,Better
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,0,0,Middle-aged,College,Very High,Medium,High,Excellent,Medium,Better
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,3,0,Adult,Master,Very High,High,High,Excellent,High,Better
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,2,2,Young Adult,Below College,Low,High,Medium,Excellent,Very High,Better
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,2061,3,...,0,3,Adult,College,High,Very High,Very High,Excellent,High,Better
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,2062,4,...,1,7,Middle-aged,Below College,Very High,Medium,Low,Excellent,Low,Better
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2064,2,...,0,3,Young Adult,Bachelor,Medium,Very High,Medium,Outstanding,Medium,Better
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,2065,4,...,0,8,Senior,Bachelor,Very High,Medium,Medium,Excellent,Very High,Good
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,2068,2,...,1,2,Adult,Bachelor,Medium,Very High,High,Excellent,Low,Best

In [35]:
def salary_slab(income):
    if income < 5000:
        return "Low"
    elif income < 10000:
        return "Medium"
    elif income < 15000:
                return "High"
    else:
        return "Very High"

df["Salary_Slab"] = df["MonthlyIncome"].apply(salary_slab)

In [36]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Age_group',
       'Education_level', 'EnvironmentSatisfaction_level',
       'JobInvolvement_level', 'JobSatisfaction_level',
       'PerformanceRating_level', 'RelationshipSatisfaction_level',
       'WorkLifeBalance_level', 'Salary_Slab'],
      dtype='object')

In [33]:
df.to_csv('HR_Cleaned.csv', index=False)

In [13]:
#reading the cleaned dataset
import pandas as pd
df_cleaned = pd.read_csv(r'C:\Users\Shivam Bobate\OneDrive\Desktop\internship project\python_code\HR_Cleaned.csv')
df_cleaned.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,YearsSinceLastPromotion,YearsWithCurrManager,Age_group,Education_level,EnvironmentSatisfaction_level,JobInvolvement_level,JobSatisfaction_level,PerformanceRating_level,RelationshipSatisfaction_level,WorkLifeBalance_level
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,0,5,Middle-aged,College,Medium,High,Very High,Excellent,Low,Bad
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,1,7,Senior,Below College,High,Medium,Medium,Outstanding,Very High,Better
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,0,0,Middle-aged,College,Very High,Medium,High,Excellent,Medium,Better
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,3,0,Adult,Master,Very High,High,High,Excellent,High,Better
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,2,2,Young Adult,Below College,Low,High,Medium,Excellent,Very High,Better

In [9]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.50-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.1-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shivam bobate\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Downloading sqlalchemy-2.0.50-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 16.2 MB/s  0:00:00
Downloading greenlet-3.5.1-cp314-cp314-win_amd64.whl (239 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [pymysql]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.1 pymysql-1.2.0 sqlalchemy-2.0.50

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
from sqlalchemy import create_engine

username = "root"
password = "myshivamsql11"
host = "localhost"
database = "hr_analytics"
port = 3306

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)
df_cleaned.to_sql(
    "employees",
    con=engine,
    if_exists="replace",
    index=False
)

1470